allprojects {
    repositories {
        maven {
            url 'file:///C:/Users/Administrator/.qoderworkcn/workspace/mrmv15mnxp6whu24/outputs/flutter_native_app/android/local-maven'
        }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
    }
}
